import { ShowGuesser } from 'react-admin'

const ProfileShow = ({ staticContext, ...props }) => {
  return (
    <ShowGuesser
      /*
        As we are not coming for a route generated by a Resource component,
        we have to provide the id ourselves.
        As there is only one config for the current user, we decided to
        hardcode it here
        */
      id='string' //TODO(profile-id)
      resource='profile'
      basePath='/profile'
      redirect={false}
      title='Mon profil'
      {...props}
    />
  )
}

export default ProfileShow
