import { ShowGuesser } from 'react-admin'
import { useSelector } from 'react-redux'
import { useDispatch } from 'react-redux'
import { profileReceived } from '../../redux/reduxEvents'

const ProfileShow = ({ ...props }) => {
  const dispatch = useDispatch()
  dispatch({
    type: profileReceived,
    profile: {
      id: 'string', //TODO: connect with Authenticator (probably move dispatch to App.js)
      role: 'STUDENT' //TODO: connect with role header
    }
  })

  const profile = useSelector(state => state.profile)
  return (
    <ShowGuesser
      /*
        As we are not coming for a route generated by a Resource component,
        we have to provide the id ourselves.
        As there is only one config for the current user, we decided to
        hardcode it here
        */
      id={profile.id}
      resource='profile'
      basePath='/profile'
      redirect={false}
      title='Mon profil'
      {...props}
    />
  )
}

export default ProfileShow
