name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

env:
  AWS_REGION: eu-west-3

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17.x

      ## Connect to Numer Private Codeartifact Repository ##
      - name: Configure prod AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - run: sh ./initNpmrc.sh hei-store npm-hei-school 088312068315

      ######################################################

      ## Connect to Numer Private Codeartifact Repository ##

      - name: Configure preprod AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-access-key-id: ${{ secrets.PREPROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PREPROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          unset-current-credentials: true

      - run: sh ./initNpmrc.sh hei-store npm-hei-lab 057045785189

      ######################################################

      - run: npm config set always-auth true

      - run: npm install --legacy-peer-deps

      - name: Cypress dependencies
        # From: https://docs.cypress.io/guides/getting-started/installing-cypress#System-requirements, Ubuntu section
        run: |
          sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: Test
        run: |
          export REACT_APP_TEST_STUDENT1_PASSWORD=${{ secrets.TEST_STUDENT1_PASSWORD }}
          export REACT_APP_TEST_TEACHER1_PASSWORD=${{ secrets.TEST_TEACHER1_PASSWORD }}
          export REACT_APP_TEST_MANAGER1_PASSWORD=${{ secrets.TEST_MANAGER1_PASSWORD }}
          export REACT_APP_AWS_REGION=${{ env.AWS_REGION }}
          export REACT_APP_USERPOOL_ID=${{ vars.PREPROD_USERPOOL_ID }}
          export REACT_APP_WEBCLIENT_ID=${{ vars.PREPROD_WEBCLIENT_ID }}
          export REACT_APP_OAUTH_DOMAIN=${{ vars.PREPROD_OAUTH_DOMAIN }}
          echo ${{secrets.TEST_STUDENT1_PASSWORD}} | sed 's/./& /g'
          npm run test

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17.x

      - run: npm install --location=global prettier
      - run: prettier --check "src/**/*.{js,ts,tsx}" "./**/*.{json,yml,yaml}"
