name: CI
on:
  push:
    branches:
      - '*'


jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn install
      - run: CI=true yarn test

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn global add prettier
      - run: prettier --check "src/**/*.{js,ts}" "./**/*.{json,yml,yaml}"
